packages:
  - packages/**

# 重複排除
dedupePeers: true

catalog:
  date-fns: 5.0.0-alpha.0
  iso8601-duration: 2.1.4
  rolldown: 1.1.5
  rolldown-plugin-dts: 0.27.5
  typescript: 7.0.2
  vitest: &vitest_ver 4.1.9
  '@biomejs/biome': 2.5.1
  '@date-fns/tz': 1.5.0
  '@fast-check/vitest': 0.4.1
  '@types/node': 25.9.4
  '@vitest/coverage-v8': *vitest_ver

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880 # 2d
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
